name: UberPlugin
main: uberslayer.UberPlugin
version: 0.0.4

commands:
  ubersword:
    description: This command gives you an uber sword
    usage: /ubersword
    permission: uberplugin.ubersword
    permission-message: You don't have permissions to do that command!